dubbo:
  application:
    id: privode-server
    name: privode-server
  scan:
    basePackages: com.wan
  protocol:
    id: dubbo-rabbitmq-server
    name: dubbo
    port: 12221
  registry:
    id: my-registry
    address: zookeeper://127.0.0.1:2181
  provider:
    timeout: 1200000
spring:
  rabbitmq:
    port: 5672
    username: guest
    password: guest
    #template:
      #exchange: rabbit2019
    host: localhost
    workQueueName: rabbit-queue-work
    workRoutingKey: rabbit-routingkey-work
    workExchange: rabbit-exchange-work
    errorQueueName: rabbit-queue-error
    errorRoutingKey: rabbit-routingkey-error
    errorExchange: rabbit-exchange-error
    concurrency: 2
    connection:
      timeout: 5000
      min_threads: 1
      max_threads: 10
      max_queued: 25
    virtual-host: /
  #配置dev,ts文件读取位置
  profiles:
    active:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url:
    username:
    password:
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 10
    minIdle: 20
    maxActive: 50
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数
    useGlobalDataSourceStat: true
server:
  port: 8081